import new glibc patches
- re-impl sigaction without race condition
- removed fstat & newfstatat syscall

as a result, cache generators can run without kernel support, so no need
to provide a default template

diff --git a/autobuild/additional-files/hooks/postinst.in b/autobuild/additional-files/hooks/postinst.in
--- a/autobuild/additional-files/hooks/postinst.in
+++ b/autobuild/additional-files/hooks/postinst.in
@@ -8,11 +8,8 @@ GDK_PIXBUF_UPDATER=@prefix@/lib/@target@/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders
 if [ -d "$GDK_PIXBUF_LOADERS_DIR" ]; then
     echo "Updating gdk-pixbuf loaders cache..." >&2
     if ! "$GDK_PIXBUF_UPDATER" --update-cache; then
-        echo "Failed to update gdk-pixbuf loaders cache." >&2
-        echo "It might be caused by not loading the old world compatibility module." >&2
-        cp -f "/usr/share/liblol/gdk-pixbuf-query-loaders.cache.default" "@prefix@/lib/@target@/gdk-pixbuf-2.0/2.10.0/loaders.cache"
-        echo "I have copied the default cache file" >&2
-        echo "Please run '$GDK_PIXBUF_UPDATER --update-cache' manually after loading" >&2
+        echo "Failed to update gdk-pixbuf loaders cache" >&2
+        echo " while running '$GDK_PIXBUF_UPDATER --update-cache'" >&2
     fi
 fi
 
@@ -22,11 +19,8 @@ GTK2_IM_UPDATER=@prefix@/lib/@target@/libgtk2.0-0/gtk-query-immodules-2.0
 if [ -d "$GTK2_IM_DIR" ]; then
     echo "Updating gtk2 immodules cache..." >&2
     if ! "$GTK2_IM_UPDATER" --update-cache; then
-        echo "Failed to update gtk2 immodules cache." >&2
-        echo "It might be caused by not loading the old world compatibility module." >&2
-        cp -f "/usr/share/liblol/gtk2-immodules.cache.default" "@prefix@/lib/@target@/gtk-2.0/2.10.0/immodules.cache"
-        echo "I have copied the default cache file" >&2
-        echo "Please run '$GTK2_IM_UPDATER --update-cache' manually after loading" >&2
+        echo "Failed to update gtk2 immodules cache" >&2
+        echo "  while running '$GTK2_IM_UPDATER --update-cache'" >&2
     fi
 fi
 
@@ -36,11 +30,8 @@ GTK3_IM_UPDATER=@prefix@/lib/@target@/libgtk-3-0/gtk-query-immodules-3.0
 if [ -d "$GTK3_IM_DIR" ]; then
     echo "Updating gtk3 immodules cache..." >&2
     if ! "$GTK3_IM_UPDATER" --update-cache; then
-        echo "Failed to update gtk3 immodules cache." >&2
-        echo "It might be caused by not loading the old world compatibility module." >&2
-        cp -f "/usr/share/liblol/gtk3-immodules.cache.default" "@prefix@/lib/@target@/gtk-3.0/3.0.0/immodules.cache"
-        echo "I have copied the default cache file" >&2
-        echo "Please run '$GTK3_IM_UPDATER --update-cache' manually after loading" >&2
+        echo "Failed to update gtk3 immodules cache" >&2
+        echo "  while running '$GTK3_IM_UPDATER --update-cache'" >&2
     fi
 fi
 
@@ -50,11 +41,8 @@ GIO_MOD_UPDATER=@prefix@/lib/@target@/glib-2.0/gio-querymodules
 if [ -d "$GIO_MOD_DIR" ]; then
     echo "Updating gio modules cache..." >&2
     if ! "$GIO_MOD_UPDATER" "$GIO_MOD_DIR"; then
-        echo "Failed to update gio modules cache." >&2
-        echo "It might be caused by not loading the old world compatibility module." >&2
-        cp -f "/usr/share/liblol/giomodule.cache.default" "@prefix@/lib/@target@/gio/modules/giomodule.cache"
-        echo "I have copied the default cache file" >&2
-        echo "Please run '$GIO_MOD_UPDATER $GIO_MOD_DIR' manually after loading" >&2
+        echo "Failed to update gio modules cache" >&2
+        echo "  while running '$GIO_MOD_UPDATER $GIO_MOD_DIR'" >&2
     fi
 fi
 
